return {
	keyCommands = {
		{combos = {{key = 'Num5', reformers = {'RCtrl','RShift'}}}, down = iCommandViewCameraToHorizont, name = _('Align camera to the Earth horizont'), category = _('View')},
		{combos = {{key = 'Num4'}}, pressed = iCommandViewLeft, up = iCommandViewLeftStop, name = _('F11 camera yaw left'), category = _('View')},
		{combos = {{key = 'Num6'}}, pressed = iCommandViewRight, up = iCommandViewRightStop, name = _('F11 camera yaw right'), category = _('View')},
		{combos = {{key = 'Num8'}}, pressed = iCommandViewUp, up = iCommandViewUpStop, name = _('F11 camera pitch up'), category = _('View')},
		{combos = {{key = 'Num2'}}, pressed = iCommandViewDown, up = iCommandViewDownStop, name = _('F11 camera pitch down'), category = _('View')},
		{combos = {{key = 'Num4', reformers = {'RShift'}}}, pressed = iCommandViewLeftFast, up = iCommandViewLeftStop, name = _('F11 camera yaw left fast'), category = _('View')},
		{combos = {{key = 'Num6', reformers = {'RShift'}}}, pressed = iCommandViewRightFast, up = iCommandViewRightStop, name = _('F11 camera yaw right fast'), category = _('View')},
		{combos = {{key = 'Num8', reformers = {'RShift'}}}, pressed = iCommandViewUpFast, up = iCommandViewUpStop, name = _('F11 camera pitch up fast'), category = _('View')},
		{combos = {{key = 'Num2', reformers = {'RShift'}}}, pressed = iCommandViewDownFast, up = iCommandViewDownStop, name = _('F11 camera pitch down fast'), category = _('View')},
		{combos = {{key = 'Num4', reformers = {'RCtrl'}}}, pressed = iCommandViewLeftSlow, up = iCommandViewLeftStop, name = _('F11 camera yaw left slow'), category = _('View')},
		{combos = {{key = 'Num6', reformers = {'RCtrl'}}}, pressed = iCommandViewRightSlow, up = iCommandViewRightStop, name = _('F11 camera yaw right slow'), category = _('View')},
		{combos = {{key = 'Num8', reformers = {'RCtrl'}}}, pressed = iCommandViewUpSlow, up = iCommandViewUpStop, name = _('F11 camera pitch up slow'), category = _('View')},
		{combos = {{key = 'Num2', reformers = {'RCtrl'}}}, pressed = iCommandViewDownSlow, up = iCommandViewDownStop, name = _('F11 camera pitch down slow'), category = _('View')},
		{combos = {{key = 'Num1'}}, pressed = iCommandViewDownLeft, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left'), category = _('View')},
		{combos = {{key = 'Num3'}}, pressed = iCommandViewDownRight, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right'), category = _('View')},
		{combos = {{key = 'Num7'}}, pressed = iCommandViewUpLeft, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left'), category = _('View')},
		{combos = {{key = 'Num9'}}, pressed = iCommandViewUpRight, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right'), category = _('View')},
		{combos = {{key = 'Num1', reformers = {'RShift'}}}, pressed = iCommandViewDownLeftFast, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left fast'), category = _('View')},
		{combos = {{key = 'Num3', reformers = {'RShift'}}}, pressed = iCommandViewDownRightFast, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right fast'), category = _('View')},
		{combos = {{key = 'Num7', reformers = {'RShift'}}}, pressed = iCommandViewUpLeftFast, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left fast'), category = _('View')},
		{combos = {{key = 'Num9', reformers = {'RShift'}}}, pressed = iCommandViewUpRightFast, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right fast'), category = _('View')},
		{combos = {{key = 'Num1', reformers = {'RCtrl'}}}, pressed = iCommandViewDownLeftSlow, up = iCommandViewDownLeftStop, name = _('F11 camera pitch down, yaw left slow'), category = _('View')},
		{combos = {{key = 'Num3', reformers = {'RCtrl'}}}, pressed = iCommandViewDownRightSlow, up = iCommandViewDownRightStop, name = _('F11 camera pitch down, yaw right slow'), category = _('View')},
		{combos = {{key = 'Num7', reformers = {'RCtrl'}}}, pressed = iCommandViewUpLeftSlow, up = iCommandViewUpLeftStop, name = _('F11 camera pitch up, yaw left slow'), category = _('View')},
		{combos = {{key = 'Num9', reformers = {'RCtrl'}}}, pressed = iCommandViewUpRightSlow, up = iCommandViewUpRightStop, name = _('F11 camera pitch up, yaw right slow'), category = _('View')},
	},
}
